# Generated by Django 4.0.4 on 2022-06-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('EnrollNo', models.CharField(max_length=15)),
                ('Branch', models.CharField(max_length=50)),
                ('Section', models.CharField(max_length=50)),
            ],
        ),
    ]
